name: lint-check
on: push
jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: checker-lint
      - run: 
        pip install poetry
        make lint