name: lint-check
on: 
  push:
    branches: [ main ]
jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        run: pip install poetry
      - name: Install Make
        run: make install
      - name: Checker-lint
        run: make lint
